import Header from "@/src/components/header/Header";
import "./globals.css";
//import styles from "./../src/styles/reset.css";
import Footer from "@/src/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <main className="w-full py-32">{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
